import express from "express";
import multer from "multer";
import AdmZip from "adm-zip";
import { CopilotClient } from "@github/copilot-sdk";
import { execSync } from "child_process";
import fs from "fs";
import path from "path";
import os from "os";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 3000;
const upload = multer({ dest: os.tmpdir(), limits: { fileSize: 50 * 1024 * 1024 } });

app.use(express.static(path.join(__dirname, "public")));
app.use(express.json());

// The agent prompt from our policy-reviewer.agent.md, adapted for SDK use
const POLICY_AGENT_PROMPT = `
You are the Policy Reviewer Agent for a data engineering organization.
Your sole purpose is to REVIEW Python and PySpark code against the
7 mandatory policies below and produce a clear, consistent, easy-to-read report.

⛔ CRITICAL CONSTRAINTS:
- You are READ-ONLY. Do NOT suggest fixes, do NOT create files, do NOT modify anything.
- Produce ONLY the report in the exact format specified.
- Check EVERY .py file provided. Do not skip files or policies.
- Every finding must cite the specific file path, line number, and a snippet.

THE 7 POLICIES:

Policy 1: No Global SparkSession
- Must NOT use SparkSession.builder.getOrCreate()
- Should receive spark as a parameter or use Databricks-provided session

Policy 2: No Hardcoded Secrets or Paths
- No hardcoded file paths (/mnt/, s3://, abfss://, etc.)
- No hardcoded passwords, API keys, tokens, emails, IPs, connection strings

Policy 3: Adequate Code Comments
- ~1 comment per 10-20 lines of code
- Files with >10 code lines and ratio worse than 1:20 should be flagged

Policy 4: Delta Tables Only
- No .format("parquet"), .format("csv"), .format("json"), .format("orc"), .format("avro")
- No CREATE TABLE USING parquet/csv/json/orc/avro

Policy 5: No Schema Creation
- No CREATE SCHEMA or CREATE DATABASE in PySpark or Spark SQL

Policy 6: Meaningful File Names
- No single-char, numeric-only, or generic names (1.py, abc.py, temp.py, script.py, etc.)
- Exempt: __init__.py, __main__.py, setup.py, conftest.py

Policy 7: No Local File Downloads
- No urllib.request.urlretrieve, subprocess curl/wget, os.system wget/curl
- No downloading files to local VM filesystem

REPORT FORMAT (use exactly this structure):

# 📋 Policy Review Report

> **⚠️ This is a READ-ONLY report. No files were modified.**

| Field | Value |
|-------|-------|
| **Repository** | \`<name>\` |
| **Scan Date** | <date> |
| **Files Scanned** | N Python file(s) |

## ✅/❌ Overall Result: **PASS/FAIL**

> N error(s), N warning(s) across N file(s)

---

## Policy Summary

| # | Policy | Status | Errors | Warnings |
|:-:|--------|:------:|:------:|:--------:|
(one row per policy)

---

## Detailed Findings

### Policy N: <Name> ✅/❌
> No violations found. ✔️
(or table of violations with Sev, File, Line, Finding)

(repeat for all 7)

---

## 📖 Policy Definitions Reference
(include the reference table)

---
*Report generated by Policy Reviewer Agent*

SEVERITY LEVELS:
- 🔴 Error — Clear policy violation
- 🟡 Warning — Potential issue

Now review the following Python files:
`;

/**
 * Extract Python files from a directory, returning their paths and contents.
 */
function getPythonFiles(dir) {
  const results = [];
  const SKIP = new Set([".git", "__pycache__", "venv", ".venv", "node_modules", "env", ".env"]);

  function walk(current, relBase) {
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      if (SKIP.has(entry.name)) continue;
      const fullPath = path.join(current, entry.name);
      const relPath = path.join(relBase, entry.name);
      if (entry.isDirectory()) {
        walk(fullPath, relPath);
      } else if (entry.name.endsWith(".py")) {
        try {
          const content = fs.readFileSync(fullPath, "utf-8");
          results.push({ path: relPath, content });
        } catch (_) { /* skip unreadable files */ }
      }
    }
  }

  walk(dir, "");
  return results;
}

/**
 * Build the full prompt with all Python file contents included.
 */
function buildPrompt(repoName, pyFiles) {
  let prompt = POLICY_AGENT_PROMPT;
  prompt += `\nRepository: ${repoName}\n`;
  prompt += `Total Python files: ${pyFiles.length}\n\n`;

  for (const file of pyFiles) {
    prompt += `--- FILE: ${file.path} ---\n`;
    prompt += file.content;
    prompt += `\n--- END FILE ---\n\n`;
  }

  prompt += `\nNow produce the complete Policy Review Report for this repository. Check every file against all 7 policies.`;
  return prompt;
}

/**
 * Run the Copilot SDK agent with the policy review prompt.
 */
async function runCopilotReview(prompt) {
  const client = new CopilotClient();
  await client.start();

  try {
    const session = await client.createSession({
      model: "gpt-4.1",
      instructions: "You are a read-only code policy auditor. You NEVER modify files. You ONLY produce reports.",
    });

    const response = await session.sendAndWait({ prompt });
    return response?.data?.content || "No response received from Copilot agent.";
  } finally {
    await client.stop();
  }
}

// ---- API Routes ----

// Health check
app.get("/api/health", (_req, res) => {
  res.json({ status: "ok", service: "policy-gate-web" });
});

// Review via GitHub repo URL
app.post("/api/review/repo", async (req, res) => {
  const { repoUrl, branch } = req.body;
  if (!repoUrl) return res.status(400).json({ error: "repoUrl is required" });

  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "pg-repo-"));

  try {
    // Parse repo name from URL
    const repoName = repoUrl.replace(/https?:\/\/github\.com\//, "").replace(/\.git$/, "").replace(/\/$/, "");

    // Clone the repository
    const cloneArgs = branch ? `--depth 1 --branch ${branch}` : "--depth 1";
    execSync(`git clone ${cloneArgs} ${repoUrl} ${tmpDir}/repo`, {
      stdio: "pipe",
      timeout: 60000,
    });

    // Find Python files
    const pyFiles = getPythonFiles(path.join(tmpDir, "repo"));
    if (pyFiles.length === 0) {
      return res.json({
        report: `# 📋 Policy Review Report\n\n> **⚠️ This is a READ-ONLY report. No files were modified.**\n\n## ✅ Overall Result: **PASS**\n\n> No Python files found in \`${repoName}\`. Nothing to review.`,
        filesScanned: 0,
      });
    }

    // Build prompt and run Copilot agent
    const prompt = buildPrompt(repoName, pyFiles);
    const report = await runCopilotReview(prompt);

    res.json({ report, filesScanned: pyFiles.length, repository: repoName });
  } catch (err) {
    console.error("Review error:", err);
    res.status(500).json({ error: err.message || "Review failed" });
  } finally {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  }
});

// Review via ZIP upload
app.post("/api/review/upload", upload.single("archive"), async (req, res) => {
  if (!req.file) return res.status(400).json({ error: "No file uploaded" });

  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "pg-zip-"));

  try {
    const projectName = req.body.projectName || path.parse(req.file.originalname).name;

    // Extract ZIP
    const zip = new AdmZip(req.file.path);
    zip.extractAllTo(tmpDir, true);

    // Find Python files
    const pyFiles = getPythonFiles(tmpDir);
    if (pyFiles.length === 0) {
      return res.json({
        report: `# 📋 Policy Review Report\n\n> **⚠️ This is a READ-ONLY report. No files were modified.**\n\n## ✅ Overall Result: **PASS**\n\n> No Python files found in uploaded archive. Nothing to review.`,
        filesScanned: 0,
      });
    }

    // Build prompt and run Copilot agent
    const prompt = buildPrompt(projectName, pyFiles);
    const report = await runCopilotReview(prompt);

    res.json({ report, filesScanned: pyFiles.length, projectName });
  } catch (err) {
    console.error("Upload review error:", err);
    res.status(500).json({ error: err.message || "Review failed" });
  } finally {
    fs.rmSync(tmpDir, { recursive: true, force: true });
    if (req.file) fs.rmSync(req.file.path, { force: true });
  }
});

app.listen(PORT, () => {
  console.log(`\n🚀 Policy Gate Web running at http://localhost:${PORT}\n`);
});
